// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTg7eTv2JcDkZbkAuRF5OcbjXTnOI9Ggw',
    appId: '1:802298935416:web:ffd3138baf0a17f429958d',
    messagingSenderId: '802298935416',
    projectId: 'findiu-2025',
    authDomain: 'findiu-2025.firebaseapp.com',
    storageBucket: 'findiu-2025.firebasestorage.app',
    measurementId: 'G-D8735J01ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUOgesXcLq1Eve5GunCeLbECQFZg6Kujo',
    appId: '1:802298935416:android:df2866b1c241dcde29958d',
    messagingSenderId: '802298935416',
    projectId: 'findiu-2025',
    storageBucket: 'findiu-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnOSgSYtJwzFHiGgdrPfw5FM1xSbADVvc',
    appId: '1:802298935416:ios:bf34c537d9d28e0d29958d',
    messagingSenderId: '802298935416',
    projectId: 'findiu-2025',
    storageBucket: 'findiu-2025.firebasestorage.app',
    iosBundleId: 'com.example.findiu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnOSgSYtJwzFHiGgdrPfw5FM1xSbADVvc',
    appId: '1:802298935416:ios:bf34c537d9d28e0d29958d',
    messagingSenderId: '802298935416',
    projectId: 'findiu-2025',
    storageBucket: 'findiu-2025.firebasestorage.app',
    iosBundleId: 'com.example.findiu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTg7eTv2JcDkZbkAuRF5OcbjXTnOI9Ggw',
    appId: '1:802298935416:web:9c99ae14eb97f87629958d',
    messagingSenderId: '802298935416',
    projectId: 'findiu-2025',
    authDomain: 'findiu-2025.firebaseapp.com',
    storageBucket: 'findiu-2025.firebasestorage.app',
    measurementId: 'G-G4C2S1XNEN',
  );

}